//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliwebAgenviaje.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:60059/LNAgenciaviaje.asmx")]
        public string ApliwebAgenviaje_localhost_LNAgenciaviaje {
            get {
                return ((string)(this["ApliwebAgenviaje_localhost_LNAgenciaviaje"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://serviceshotel.somee.com/WServiceHotel.asmx")]
        public string ApliwebAgenviaje_com_somee_serviceshotel_WServiceHotel {
            get {
                return ((string)(this["ApliwebAgenviaje_com_somee_serviceshotel_WServiceHotel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hotelvalparaiso.somee.com/HotelWS.asmx")]
        public string ApliwebAgenviaje_com_somee_hotelvalparaiso_HotelWS {
            get {
                return ((string)(this["ApliwebAgenviaje_com_somee_hotelvalparaiso_HotelWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agenciaviajeabjsanti.somee.com/AgenciaViajeLAB_SCSJ.asmx")]
        public string ApliwebAgenviaje_com_somee_agenciaviajeabjsanti_AgenciaViajeLAB_SCSJ {
            get {
                return ((string)(this["ApliwebAgenviaje_com_somee_agenciaviajeabjsanti_AgenciaViajeLAB_SCSJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.webservicesautos.somee.com/WebServiceAUTOS.asmx")]
        public string ApliwebAgenviaje_com_somee_webservicesautos_www_WebServiceAUTOS {
            get {
                return ((string)(this["ApliwebAgenviaje_com_somee_webservicesautos_www_WebServiceAUTOS"]));
            }
        }
    }
}
